### ISSUE TITLE
mutagen.easyid3.EasyID3KeyError: u'replaygain_seratogain_gain'

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#215]
Originally reported by: **ada mancini (Bitbucket: [adamancini](http://bitbucket.org/adamancini), GitHub: [adamancini](http://github.com/adamancini))**

----------------------------------------

Mutagen keeps giving me this error message whenever this script I'm using goes to scan my library.  
```
#!

(virtualenv)hypgnosis@stew ~/gmusicapi-scripts $ ./gmsync.py up -d "/home/hypgnosis/files/Music/Music/"
/home/hypgnosis/virtualenv/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Successfully logged in.
 
Loading Google Music songs...
Filtered 0 Google Music songs
Loaded 560 Google Music songs
 
Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 757 local songs.
 
Scanning for missing songs...
Traceback (most recent call last):
  File "./gmsync.py", line 202, in <module>
    main()
  File "./gmsync.py", line 164, in main
    upload_songs = compare_song_collections(local_songs, google_songs)
  File "/mnt/sdd1/hypgnosis/gmusicapi-scripts/gmwrapper.py", line 49, in compare_song_collections
    src_key = create_song_key(src_song)
  File "/mnt/sdd1/hypgnosis/gmusicapi-scripts/gmwrapper.py", line 68, in create_song_key
    song = song if isinstance(song, dict) else _mutagen_fields_to_single_value(song)
  File "/mnt/sdd1/hypgnosis/gmusicapi-scripts/gmwrapper.py", line 35, in _mutagen_fields_to_single_value
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
  File "/home/hypgnosis/virtualenv/lib/python2.7/site-packages/mutagen/_util.py", line 130, in <lambda>
    iteritems = lambda s: iter(s.items())
  File "/home/hypgnosis/virtualenv/lib/python2.7/site-packages/mutagen/_util.py", line 127, in items
    return list(zip(self.keys(), self.values()))
  File "/home/hypgnosis/virtualenv/lib/python2.7/site-packages/mutagen/_util.py", line 121, in values
    return [self[k] for k in self.keys()]
  File "/home/hypgnosis/virtualenv/lib/python2.7/site-packages/mutagen/_file.py", line 54, in __getitem__
    return self.tags[key]
  File "/home/hypgnosis/virtualenv/lib/python2.7/site-packages/mutagen/easyid3.py", line 196, in __getitem__
    return func(self.__id3, key)
  File "/home/hypgnosis/virtualenv/lib/python2.7/site-packages/mutagen/easyid3.py", line 385, in gain_get
    raise EasyID3KeyError(key)
mutagen.easyid3.EasyID3KeyError: u'replaygain_seratogain_gain'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/215

**Comment by lazka** [comment]
Some related error on bitbucket: https://bitbucket.org/lazka/mutagen/issues/258/

**Comment by lazka** [comment]
Can't figure it out, requested the file here: https://bitbucket.org/lazka/mutagen/issues/258/#comment-28788944
