### ISSUE TITLE
EasyMP4.RegisterIntKey does not create usable mappings

### ISSUE THREAD

**Issue by lazka** [quodlibet/mutagen#250]
Originally reported by: **Jason Penney (Bitbucket: [jpenney](http://bitbucket.org/jpenney), GitHub: [jpenney](http://github.com/jpenney))**

---

It doesn't seem like it's possible to use the the keys added by `EasyMP4.RegisterIntKey`

``` .python
>>> mutagen.easymp4.EasyMP4Tags.RegisterIntKey('rating', 'rtng')
>>> tagger = mutagen.File(pth, easy=True)
>>> type(tagger)
<class 'mutagen.easymp4.EasyMP4'>

>>> tagger['rating'] = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jpenney/.virtualenvs/graphic_audio_tagger/lib/python2.7/site-packages/mutagen/_file.py", line 67, in __setitem__
    self.tags[key] = value
  File "/Users/jpenney/.virtualenvs/graphic_audio_tagger/lib/python2.7/site-packages/mutagen/easymp4.py", line 197, in __setitem__
    return func(self.__mp4, key, value)
  File "/Users/jpenney/.virtualenvs/graphic_audio_tagger/lib/python2.7/site-packages/mutagen/easymp4.py", line 108, in setter
    tags[atomid] = [clamp(v) for v in map(int, value)]
TypeError: argument 2 to map() must support iteration

>>> tagger['rating'] = [0]
>>> tagger.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jpenney/.virtualenvs/graphic_audio_tagger/lib/python2.7/site-packages/mutagen/_file.py", line 130, in save
    return self.tags.save(filename, **kwargs)
  File "/Users/jpenney/.virtualenvs/graphic_audio_tagger/lib/python2.7/site-packages/mutagen/mp4/__init__.py", line 375, in save
    values.append(render_func(self, key, value))
  File "/Users/jpenney/.virtualenvs/graphic_audio_tagger/lib/python2.7/site-packages/mutagen/mp4/__init__.py", line 764, in __render_text
    v = v.decode("utf-8")
AttributeError: 'int' object has no attribute 'decode'
```

---
- Bitbucket: https://bitbucket.org/lazka/mutagen/issue/250

**Comment by lazka** [comment]
Because atom types are hardcoded in mp4 and RegisterIntKey only works with already implemented atoms.
