### ISSUE TITLE
Overeager deprecation warnings

### ISSUE THREAD

**Issue by sampsyo** [quodlibet/mutagen#261]
I noticed today while running the beets tests against Mutagen 1.33 that I started getting deprecation warnings like this:

```
/Users/asampson/Library/Python/2.7/lib/python/site-packages/mutagen/_file.py:138: DeprecationWarning: save(filename=...) is deprecated, reload the file
  DeprecationWarning)
```

but we don't use that deprecated `filename=` parameter. In fact, a really simple test script triggers the deprecation warning in master:

```
$ cat t.py
import mutagen
x = mutagen.File('x.m4a')
x.save()
$ python -W error t.py
Traceback (most recent call last):
  File "t.py", line 3, in <module>
    x.save()
  File "/Users/asampson/code/mutagen/mutagen/mp4/__init__.py", line 1014, in save
    super(MP4, self).save(*args, **kwargs)
  File "/Users/asampson/code/mutagen/mutagen/_util.py", line 98, in wrapper
    return func(self, h, *args, **kwargs)
  File "/Users/asampson/code/mutagen/mutagen/_file.py", line 138, in save
    DeprecationWarning)
DeprecationWarning: save(filename=...) is deprecated, reload the file
```

This isn't a big deal because users don't see this message, but `nose`'s defaults happened to make it appear. But I thought you might like to know anyway.

**Comment by lazka** [comment]
Thanks
