### ISSUE TITLE
Mp4 error if track has no audio data

### ISSUE THREAD

**Issue by mrta** [quodlibet/mutagen#272]
If Mp4 has no audio data this is the error. But i would like to edit my mp4 file even if there is no audio data

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_util.py", line 131, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 295, in File
    return Kind(fileobj, filename=filething.filename)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_util.py", line 123, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/mp4/__init__.py", line 991, in load
    self.info = MP4Info(atoms, fileobj)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_util.py", line 152, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/mp4/__init__.py", line 874, in __init__
    raise MP4StreamInfoError("track has no audio data")
mutagen.mp4.MP4StreamInfoError: track has no audio data

**Comment by lazka** [comment]
> If Mp4 has no audio data this is the error. But i would like to edit my mp4 file even if there is no audio data

What are you trying to do?

**Comment by mrta** [comment]
mutagen.File(filepath)

or

from mutagen.mp4 import MP4
MP4(filepath)

**Comment by lazka** [comment]
I mean what is your use case. mutagen is an **audio** metadata library after all

**Comment by mrta** [comment]
My use case is tagging mp4 files. Often files with video and audio track. Sometimes without audio track.

**Comment by lazka** [comment]
ok
