### ISSUE TITLE
Duration handling for broken flac files

### ISSUE THREAD

**Issue by gfarmerfr** [quodlibet/mutagen#287]
Hi,

I stumble upon some broken flac files in the wild that doesn't report a correct length (duration).

Prior to 1.36 they were reporting a duration of 0.0:
```
>>> import mutagen
>>> audio = mutagen.File("test.flac")
>>> audio.info.length
0.0
```

With 1.36 it's actually raising a ZeroDivisionError:

```
>>> import mutagen
>>> audio = mutagen.File("test.flac")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python2.7/site-packages/mutagen/_util.py", line 131, in wrapper_func
    return func(h, *args, **kwargs)
  File "venv/lib/python2.7/site-packages/mutagen/_file.py", line 295, in File
    return Kind(fileobj, filename=filething.filename)
  File "venv/lib/python2.7/site-packages/mutagen/_file.py", line 48, in __init__
    self.load(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/mutagen/_util.py", line 152, in wrapper
    return func(*args, **kwargs)
  File "venv/lib/python2.7/site-packages/mutagen/_util.py", line 123, in wrapper
    return func(self, h, *args, **kwargs)
  File "venv/lib/python2.7/site-packages/mutagen/flac.py", line 801, in load
    float(fileobj.tell() - start) * 8 / self.info.length)
ZeroDivisionError: float division by zero
```

I think this was introduced by adding the bitrate info in this commit: https://github.com/quodlibet/mutagen/commit/d8aed5afcf32cdddea30fdaf812e1f2c25c6d3e6

If you decide to handle this type of broken files should the bitrate be 0 ?

**Comment by lazka** [comment]
Thanks

**Comment by gfarmerfr** [comment]
No problem, thx for the patch.
