### ISSUE TITLE
windows 32-bit support?

### ISSUE THREAD

**Issue by bll123** [quodlibet/mutagen#332]
mutagen 1.39 on 32-bit windows XP.
I don't know if you still want to bother supporting 32-bit windows.
I haven't done any research on this API to see if there is some microsoft update I can install to support it.
```

C:\Documents and Settings\bll\Desktop\BallroomDJ\test.dir>c:\Python27\python.exe
 C:\Python27\Scripts\mutagen-inspect test-files\waltz.mp3
Traceback (most recent call last):
  File "C:\Python27\Scripts\mutagen-inspect", line 12, in <module>
    from mutagen._tools.mutagen_inspect import entry_point
  File "c:\Python27\lib\site-packages\mutagen\_tools\mutagen_inspect.py", line 11, in <module>
    from mutagen._senf import print_, argv
  File "c:\Python27\lib\site-packages\mutagen\_senf\__init__.py", line 29, in <module>
    from ._fsnative import fsnative, path2fsn, fsn2text, fsn2bytes, \
  File "c:\Python27\lib\site-packages\mutagen\_senf\_fsnative.py", line 28, in <module>
    from . import _winapi as winapi
  File "c:\Python27\lib\site-packages\mutagen\_senf\_winapi.py", line 194, in <module>
    GetFileInformationByHandleEx = kernel32.GetFileInformationByHandleEx
  File "c:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "c:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GetFileInformationByHandleEx' not found
```

**Comment by lazka** [comment]
Hm, yeah, that API is Vista+

**Comment by lazka** [comment]
Either `pip install "git+https://github.com/quodlibet/mutagen.git"` or downgrade with `pip install mutagen==1.38`
