### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by neal1991** [quodlibet/mutagen#341]
I am trying to obtain the length of a mp3 file.
```
from mutagen.mp3 import MP3

def get_voice_length():
    duration = MP3('audio.mp3')
```
but the initial of MP3 will create error:
```
Traceback (most recent call last):
  File "C:\python36\lib\site-packages\mutagen\_util.py", line 235, in _openfile
    fileobj = open(filename, "rb+" if writable else "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'audio.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/neal1/project/voicer/app.py", line 83, in <module>
    get_voice_length()
  File "C:/Users/neal1/project/voicer/app.py", line 71, in get_voice_length
    duration = MP3('audio.mp3')
  File "C:\python36\lib\site-packages\mutagen\_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "C:\python36\lib\site-packages\mutagen\_util.py", line 139, in wrapper
    writable, create) as h:
  File "C:\python36\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\python36\lib\site-packages\mutagen\_util.py", line 256, in _openfile
    raise MutagenError(e)
mutagen.MutagenError: [Errno 2] No such file or directory: 'audio.mp3'
```

The mp3 file does exists.  I have tried relative file path and absolute file path. Both don't work.

**Comment by lazka** [comment]
> The mp3 file does exists

I doubt that, you probably missed something

**Comment by neal1991** [comment]
Sorry for my mistake, the name is incorrect

**Comment by lazka** [comment]
no problem :)
