### ISSUE TITLE
 struct.error when processing an id3 file 

### ISSUE THREAD

**Issue by jvoisin** [quodlibet/mutagen#421]
When running the following python script with the [attached file]( 
https://github.com/quodlibet/mutagen/files/3964085/crash-e2914adbab653bdc759173a82ea94a2a1241fc817ae2d67d5c785e76b1c9a27b.zip
 ), mutagen throws a `struct.error` exception:

```python
import mutagen, sys

mutagen.File(sys.argv[1])
```

```python
$ python3 mutest.py crash-e2914adbab653bdc759173a82ea94a2a1241fc817ae2d67d5c785e76b1c9a27b
Traceback (most recent call last):
  File "mutest.py", line 3, in <module>
    mutagen.File(sys.argv[1])
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_util.py", line 148, in wrapper_func
    return func(h, *args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_file.py", line 300, in File
    return Kind(fileobj, filename=filething.filename)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_file.py", line 411, in load
    self.tags = ID3(fileobj, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_file.py", line 77, in __init__
    super(ID3, self).__init__(*args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_tags.py", line 178, in __init__
    super(ID3Tags, self).__init__(*args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_util.py", line 533, in __init__
    super(DictProxy, self).__init__(*args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_tags.py", line 111, in __init__
    self.load(*args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_file.py", line 173, in load
    remaining_data = self._read(self._header, data)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_tags.py", line 182, in _read
    header, data, header.known_frames)
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_tags.py", line 596, in read_frames
    result.append(tag._fromData(id3, flags, framedata))
  File "/home/jvoisin/app/AFL/ven/lib/python3.7/site-packages/mutagen/id3/_frames.py", line 280, in _fromData
    usize, = unpack('>L', data[:4])
struct.error: unpack requires a buffer of 4 bytes
zsh: exit 1     python3 mutest.py 
$
```

**Comment by phw** [comment]
This got fixed for mutagen 1.45.0 with https://github.com/quodlibet/mutagen/commit/3d6b40533e5425ee942be64d02b54a234c3ffc99
