### ISSUE TITLE
Mutagen ID3 No header error

### ISSUE THREAD

**Issue by Silverarmor** [quodlibet/mutagen#502]
```
Traceback (most recent call last): File "/home/sjoerdhilhorst/.local/bin/spotdl", line 8, in <module> sys.exit(console_entry_point()) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/spotdl/__main__.py", line 100, in console_entry_point downloader.download_single_song(song) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/spotdl/download/downloader.py", line 274, in download_single_song download_song(songObj, self.displayManager, self.downloadTracker) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/spotdl/download/downloader.py", line 170, in download_song audioFile = EasyID3(convertedFilePath) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/mutagen/easyid3.py", line 169, in __init__ self.load(filename) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/mutagen/_util.py", line 185, in wrapper return func(*args, **kwargs) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/mutagen/_util.py", line 156, in wrapper return func(self, h, *args, **kwargs) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/mutagen/id3/_file.py", line 152, in load self._header = ID3Header(fileobj) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/mutagen/_util.py", line 185, in wrapper return func(*args, **kwargs) File "/home/sjoerdhilhorst/.local/lib/python3.6/site-packages/mutagen/id3/_tags.py", line 59, in __init__ raise ID3NoHeaderError("%s: too small" % fn) mutagen.id3._util.ID3NoHeaderError: ./Yotto - Marisa.mp3: too small
```

See https://github.com/spotDL/spotify-downloader/issues/934

**Comment by pianographe** [comment]
Hello,

Same issue here, also exists when I try to resume the previously failed download:

`
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/usr/local/lib/python3.7/dist-packages/spotdl/download/downloader.py", line 170, in download_song
    audioFile = EasyID3(convertedFilePath)
  File "/usr/local/lib/python3.7/dist-packages/mutagen/easyid3.py", line 169, in __init__
    self.load(filename)
  File "/usr/local/lib/python3.7/dist-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mutagen/_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mutagen/id3/_file.py", line 152, in load
    self._header = ID3Header(fileobj)
  File "/usr/local/lib/python3.7/dist-packages/mutagen/_util.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mutagen/id3/_tags.py", line 59, in __init__
    raise ID3NoHeaderError("%s: too small" % fn)
mutagen.id3._util.ID3NoHeaderError: ./Rekinsa - Better Dayz.mp3: too small
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/spotdl", line 10, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.7/dist-packages/spotdl/__main__.py", line 120, in console_entry_point
    downloader.resume_download_from_tracking_file(request)
  File "/usr/local/lib/python3.7/dist-packages/spotdl/download/downloader.py", line 323, in resume_download_from_tracking_file
    for song in songObjList
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
mutagen.id3._util.ID3NoHeaderError: ./Rekinsa - Better Dayz.mp3: too small
`

Running a fresh new VPS with Debian 10 Buster stable and latest Python3 (v.3.7.3)

**Comment by lazka** [comment]
Are you sure the file is an mp3 file and it has some content?

**Comment by Silverarmor** [comment]
File seems to be 0 bytes reported by Windows explorer.
cc @Mikhail-Zex

**Comment by lazka** [comment]
Thanks! So I'd say this is not a mutagen problem :)

**Comment by Mikhail-Zex** [comment]
Well we are covering an `.mp4` to `.mp3` using ffmpeg. Ffmpeg works like a chard so it should be having something written to the file.

**Comment by lazka** [comment]
There is no check that the call to ffmpeg actually worked: https://github.com/spotDL/spotify-downloader/blob/5441b0cdb0e89d9d003e6f68240fa5e45f627144/spotdl/download/downloader.py#L154

So likely ffmpeg failed.

**Comment by Mikhail-Zex** [comment]
Ok. I'll get a test run done and get back to you.

**Comment by Mikhail-Zex** [comment]
Still not working.

**Comment by Mikhail-Zex** [comment]
Ok the issue may be due to ffmpeg conversion. I'll get back to you if it's not an ffmpeg glitch.

P.S.
The `check=True` didn't fix it.

**Comment by mikeblas** [comment]
> and there is a while loop to check if a non-empty output file is created.

This while loop doesn't work as you expect. It will exit even if the file is empty. If the file is never created, it will hang. While that loop runs, it uses 100% CPU since it never yields any time.
